---
abstract: 'copy modules(.pm) to cwd or somewhere'
author:
  - 'sunnavy <sunnavy@bestpractical.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102341, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-moduleshere
recommends:
  File::Copy::Recursive: 0
resources:
  repository: http://github.com/bestpractical/app-moduleshere.git
version: 0.07
