---
abstract: 'copy modules(.pm) to cwd or somewhere'
author:
  - 'sunnavy <sunnavy@bestpractical.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101040'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-moduleshere
recommends: {}
requires: {}
version: 0.01
